import { auth } from '@clerk/nextjs/server'
import { NextResponse } from 'next/server'
import { getOctokit } from '@/lib/octokit'
import { commitFile, getUserRole, listProjects } from '@/lib/github'
import { clerkClient } from '@clerk/nextjs/server'

const ORG = process.env.GITHUB_ORG!
const REPO = process.env.GITHUB_REPO!

export async function GET() {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: 'Unauthenticated' }, { status: 401 })

  const octokit = await getOctokit()
  const projects = await listProjects(octokit)
  return NextResponse.json({ projects })
}

export async function POST(req: Request) {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: 'Unauthenticated' }, { status: 401 })

  const client = await clerkClient()
  const user = await client.users.getUser(userId)
  const username = user.externalAccounts.find(a => a.provider === 'oauth_github')?.username
  if (!username) return NextResponse.json({ error: 'No GitHub account linked' }, { status: 400 })

  const octokit = await getOctokit()
  const role = await getUserRole(octokit, username)
  if (role !== 'reviewer') return NextResponse.json({ error: 'Only reviewers can create projects' }, { status: 403 })

  const { slug } = await req.json()
  if (!slug || !/^[a-z0-9-]+$/.test(slug)) {
    return NextResponse.json({ error: 'Invalid slug — use lowercase letters, numbers, and hyphens only' }, { status: 400 })
  }

  const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'

  const files: Array<{ path: string; content: string }> = [
    {
      path: `projects/${slug}/docs/index.mdx`,
      content: `# ${slug}\n\nWelcome to the **${slug}** documentation.\n`,
    },
    {
      path: `projects/${slug}/package.json`,
      content: JSON.stringify({
        name: slug,
        version: '0.0.1',
        private: true,
        scripts: { build: 'docusaurus build' },
        overrides: { webpack: '5.105.0' },
        dependencies: {
          '@docusaurus/core': '3.10.0',
          '@docusaurus/preset-classic': '3.10.0',
          clsx: '2.1.1',
          react: '19.0.0',
          'react-dom': '19.0.0',
        },
      }, null, 2) + '\n',
    },
    {
      path: `projects/${slug}/docusaurus.config.js`,
      content: `// @ts-check\n\n/** @type {import('@docusaurus/types').Config} */\nconst config = {\n  title: '${slug}',\n  url: '${APP_URL}',\n  baseUrl: '/docs/${slug}/',\n  onBrokenLinks: 'warn',\n  onBrokenMarkdownLinks: 'warn',\n  trailingSlash: false,\n  presets: [\n    [\n      'classic',\n      /** @type {import('@docusaurus/preset-classic').Options} */\n      ({\n        docs: {\n          routeBasePath: '/',\n          sidebarPath: require.resolve('./sidebars.js'),\n        },\n        blog: false,\n      }),\n    ],\n  ],\n};\n\nmodule.exports = config;\n`,
    },
    {
      path: `projects/${slug}/sidebars.js`,
      content: `/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */\nconst sidebars = {\n  docs: [{ type: 'autogenerated', dirName: '.' }],\n};\n\nmodule.exports = sidebars;\n`,
    },
    {
      path: `projects/${slug}/.gitignore`,
      content: `.docusaurus\nnode_modules\nbuild\n`,
    },
  ]

  // Commit all files sequentially (each needs previous to exist for SHA tracking — they're new so no SHA needed)
  for (const file of files) {
    await commitFile(octokit, file.path, file.content, `feat: initialise project ${slug}`, 'main')
  }

  return NextResponse.json({ ok: true, slug })
}
